// Based on RoyaleAPI cr-api-data (cards.json); the block at the bottom was
// added from the official Clash Royale /v1/cards endpoint because the
// RoyaleAPI snapshot predates those cards.
export interface RawCard {
  key: string
  name: string
  elixir: number
  type: 'Troop' | 'Building' | 'Spell'
  rarity: 'Common' | 'Rare' | 'Epic' | 'Legendary' | 'Champion'
  arena: number
}

export const RAW_CARDS: RawCard[] = [
  { key: 'knight', name: 'Knight', elixir: 3, type: 'Troop', rarity: 'Common', arena: 0 },
  { key: 'archers', name: 'Archers', elixir: 3, type: 'Troop', rarity: 'Common', arena: 0 },
  { key: 'goblins', name: 'Goblins', elixir: 2, type: 'Troop', rarity: 'Common', arena: 1 },
  { key: 'giant', name: 'Giant', elixir: 5, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'pekka', name: 'P.E.K.K.A', elixir: 7, type: 'Troop', rarity: 'Epic', arena: 6 },
  { key: 'minions', name: 'Minions', elixir: 3, type: 'Troop', rarity: 'Common', arena: 0 },
  { key: 'balloon', name: 'Balloon', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 7 },
  { key: 'witch', name: 'Witch', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 6 },
  { key: 'barbarians', name: 'Barbarians', elixir: 5, type: 'Troop', rarity: 'Common', arena: 3 },
  { key: 'golem', name: 'Golem', elixir: 8, type: 'Troop', rarity: 'Epic', arena: 10 },
  { key: 'skeletons', name: 'Skeletons', elixir: 1, type: 'Troop', rarity: 'Common', arena: 2 },
  { key: 'valkyrie', name: 'Valkyrie', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 2 },
  { key: 'skeleton-army', name: 'Skeleton Army', elixir: 3, type: 'Troop', rarity: 'Epic', arena: 6 },
  { key: 'bomber', name: 'Bomber', elixir: 2, type: 'Troop', rarity: 'Common', arena: 2 },
  { key: 'musketeer', name: 'Musketeer', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'baby-dragon', name: 'Baby Dragon', elixir: 4, type: 'Troop', rarity: 'Epic', arena: 6 },
  { key: 'prince', name: 'Prince', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 7 },
  { key: 'wizard', name: 'Wizard', elixir: 5, type: 'Troop', rarity: 'Rare', arena: 4 },
  { key: 'mini-pekka', name: 'Mini P.E.K.K.A', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'spear-goblins', name: 'Spear Goblins', elixir: 2, type: 'Troop', rarity: 'Common', arena: 1 },
  { key: 'giant-skeleton', name: 'Giant Skeleton', elixir: 6, type: 'Troop', rarity: 'Epic', arena: 8 },
  { key: 'hog-rider', name: 'Hog Rider', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 5 },
  { key: 'minion-horde', name: 'Minion Horde', elixir: 5, type: 'Troop', rarity: 'Common', arena: 10 },
  { key: 'ice-wizard', name: 'Ice Wizard', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 12 },
  { key: 'royal-giant', name: 'Royal Giant', elixir: 6, type: 'Troop', rarity: 'Common', arena: 7 },
  { key: 'guards', name: 'Guards', elixir: 3, type: 'Troop', rarity: 'Epic', arena: 6 },
  { key: 'princess', name: 'Princess', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'dark-prince', name: 'Dark Prince', elixir: 4, type: 'Troop', rarity: 'Epic', arena: 7 },
  { key: 'three-musketeers', name: 'Three Musketeers', elixir: 9, type: 'Troop', rarity: 'Rare', arena: 7 },
  { key: 'lava-hound', name: 'Lava Hound', elixir: 7, type: 'Troop', rarity: 'Legendary', arena: 13 },
  { key: 'ice-spirit', name: 'Ice Spirit', elixir: 1, type: 'Troop', rarity: 'Common', arena: 8 },
  { key: 'fire-spirit', name: 'Fire Spirit', elixir: 1, type: 'Troop', rarity: 'Common', arena: 4 },
  { key: 'miner', name: 'Miner', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'sparky', name: 'Sparky', elixir: 6, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'bowler', name: 'Bowler', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 13 },
  { key: 'lumberjack', name: 'Lumberjack', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 14 },
  { key: 'battle-ram', name: 'Battle Ram', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 3 },
  { key: 'inferno-dragon', name: 'Inferno Dragon', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'ice-golem', name: 'Ice Golem', elixir: 2, type: 'Troop', rarity: 'Rare', arena: 8 },
  { key: 'mega-minion', name: 'Mega Minion', elixir: 3, type: 'Troop', rarity: 'Rare', arena: 3 },
  { key: 'dart-goblin', name: 'Dart Goblin', elixir: 3, type: 'Troop', rarity: 'Rare', arena: 9 },
  { key: 'goblin-gang', name: 'Goblin Gang', elixir: 3, type: 'Troop', rarity: 'Common', arena: 9 },
  { key: 'electro-wizard', name: 'Electro Wizard', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'elite-barbarians', name: 'Elite Barbarians', elixir: 6, type: 'Troop', rarity: 'Common', arena: 10 },
  { key: 'hunter', name: 'Hunter', elixir: 4, type: 'Troop', rarity: 'Epic', arena: 10 },
  { key: 'executioner', name: 'Executioner', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 14 },
  { key: 'bandit', name: 'Bandit', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 13 },
  { key: 'royal-recruits', name: 'Royal Recruits', elixir: 7, type: 'Troop', rarity: 'Common', arena: 7 },
  { key: 'night-witch', name: 'Night Witch', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 14 },
  { key: 'bats', name: 'Bats', elixir: 2, type: 'Troop', rarity: 'Common', arena: 5 },
  { key: 'royal-ghost', name: 'Royal Ghost', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 12 },
  { key: 'ram-rider', name: 'Ram Rider', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'zappies', name: 'Zappies', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 10 },
  { key: 'rascals', name: 'Rascals', elixir: 5, type: 'Troop', rarity: 'Common', arena: 13 },
  { key: 'cannon-cart', name: 'Cannon Cart', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 15 },
  { key: 'mega-knight', name: 'Mega Knight', elixir: 7, type: 'Troop', rarity: 'Legendary', arena: 11 },
  { key: 'skeleton-barrel', name: 'Skeleton Barrel', elixir: 3, type: 'Troop', rarity: 'Common', arena: 9 },
  { key: 'flying-machine', name: 'Flying Machine', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 5 },
  { key: 'wall-breakers', name: 'Wall Breakers', elixir: 2, type: 'Troop', rarity: 'Epic', arena: 12 },
  { key: 'royal-hogs', name: 'Royal Hogs', elixir: 5, type: 'Troop', rarity: 'Rare', arena: 7 },
  { key: 'goblin-giant', name: 'Goblin Giant', elixir: 6, type: 'Troop', rarity: 'Epic', arena: 9 },
  { key: 'fisherman', name: 'Fisherman', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 15 },
  { key: 'magic-archer', name: 'Magic Archer', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 13 },
  { key: 'electro-dragon', name: 'Electro Dragon', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 12 },
  { key: 'firecracker', name: 'Firecracker', elixir: 3, type: 'Troop', rarity: 'Common', arena: 12 },
  { key: 'mighty-miner', name: 'Mighty Miner', elixir: 4, type: 'Troop', rarity: 'Champion', arena: 17 },
  { key: 'super-witch', name: 'Super Witch', elixir: 6, type: 'Troop', rarity: 'Legendary', arena: 5 },
  { key: 'elixir-golem', name: 'Elixir Golem', elixir: 3, type: 'Troop', rarity: 'Rare', arena: 14 },
  { key: 'battle-healer', name: 'Battle Healer', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 8 },
  { key: 'skeleton-king', name: 'Skeleton King', elixir: 4, type: 'Troop', rarity: 'Champion', arena: 16 },
  { key: 'super-lava-hound', name: 'Super Lava Hound', elixir: 8, type: 'Troop', rarity: 'Legendary', arena: 10 },
  { key: 'super-magic-archer', name: 'Super Magic Archer', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 13 },
  { key: 'archer-queen', name: 'Archer Queen', elixir: 5, type: 'Troop', rarity: 'Champion', arena: 17 },
  { key: 'santa-hog-rider', name: 'Santa Hog Rider', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 5 },
  { key: 'golden-knight', name: 'Golden Knight', elixir: 4, type: 'Troop', rarity: 'Champion', arena: 16 },
  { key: 'super-ice-golem', name: 'Super Ice Golem', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 8 },
  { key: 'monk', name: 'Monk', elixir: 5, type: 'Troop', rarity: 'Champion', arena: 18 },
  { key: 'super-archers', name: 'Super Archers', elixir: 3, type: 'Troop', rarity: 'Legendary', arena: 24 },
  { key: 'skeleton-dragons', name: 'Skeleton Dragons', elixir: 4, type: 'Troop', rarity: 'Common', arena: 4 },
  { key: 'terry', name: 'Terry', elixir: 4, type: 'Troop', rarity: 'Champion', arena: 16 },
  { key: 'super-mini-pekka', name: 'Super Mini P.E.K.K.A', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 14 },
  { key: 'mother-witch', name: 'Mother Witch', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 15 },
  { key: 'electro-spirit', name: 'Electro Spirit', elixir: 1, type: 'Troop', rarity: 'Common', arena: 4 },
  { key: 'electro-giant', name: 'Electro Giant', elixir: 7, type: 'Troop', rarity: 'Epic', arena: 13 },
  { key: 'raging-prince', name: 'Raging Prince', elixir: 5, type: 'Troop', rarity: 'Epic', arena: 7 },
  { key: 'phoenix', name: 'Phoenix', elixir: 4, type: 'Troop', rarity: 'Legendary', arena: 12 },
  { key: 'cannon', name: 'Cannon', elixir: 3, type: 'Building', rarity: 'Common', arena: 3 },
  { key: 'goblin-hut', name: 'Goblin Hut', elixir: 5, type: 'Building', rarity: 'Rare', arena: 1 },
  { key: 'mortar', name: 'Mortar', elixir: 4, type: 'Building', rarity: 'Common', arena: 5 },
  { key: 'inferno-tower', name: 'Inferno Tower', elixir: 5, type: 'Building', rarity: 'Rare', arena: 4 },
  { key: 'bomb-tower', name: 'Bomb Tower', elixir: 4, type: 'Building', rarity: 'Rare', arena: 4 },
  { key: 'barbarian-hut', name: 'Barbarian Hut', elixir: 6, type: 'Building', rarity: 'Rare', arena: 9 },
  { key: 'tesla', name: 'Tesla', elixir: 4, type: 'Building', rarity: 'Common', arena: 10 },
  { key: 'elixir-collector', name: 'Elixir Collector', elixir: 6, type: 'Building', rarity: 'Rare', arena: 15 },
  { key: 'x-bow', name: 'X-Bow', elixir: 6, type: 'Building', rarity: 'Epic', arena: 10 },
  { key: 'tombstone', name: 'Tombstone', elixir: 3, type: 'Building', rarity: 'Rare', arena: 2 },
  { key: 'furnace', name: 'Furnace', elixir: 4, type: 'Building', rarity: 'Rare', arena: 10 },
  { key: 'goblin-cage', name: 'Goblin Cage', elixir: 4, type: 'Building', rarity: 'Rare', arena: 1 },
  { key: 'goblin-drill', name: 'Goblin Drill', elixir: 4, type: 'Building', rarity: 'Epic', arena: 14 },
  { key: 'party-hut', name: 'Party Hut', elixir: 5, type: 'Building', rarity: 'Legendary', arena: 10 },
  { key: 'fireball', name: 'Fireball', elixir: 4, type: 'Spell', rarity: 'Rare', arena: 0 },
  { key: 'arrows', name: 'Arrows', elixir: 3, type: 'Spell', rarity: 'Common', arena: 0 },
  { key: 'rage', name: 'Rage', elixir: 2, type: 'Spell', rarity: 'Epic', arena: 14 },
  { key: 'rocket', name: 'Rocket', elixir: 6, type: 'Spell', rarity: 'Rare', arena: 5 },
  { key: 'goblin-barrel', name: 'Goblin Barrel', elixir: 3, type: 'Spell', rarity: 'Epic', arena: 6 },
  { key: 'freeze', name: 'Freeze', elixir: 4, type: 'Spell', rarity: 'Epic', arena: 8 },
  { key: 'mirror', name: 'Mirror', elixir: 1, type: 'Spell', rarity: 'Epic', arena: 15 },
  { key: 'lightning', name: 'Lightning', elixir: 6, type: 'Spell', rarity: 'Epic', arena: 8 },
  { key: 'zap', name: 'Zap', elixir: 2, type: 'Spell', rarity: 'Common', arena: 5 },
  { key: 'poison', name: 'Poison', elixir: 4, type: 'Spell', rarity: 'Epic', arena: 9 },
  { key: 'graveyard', name: 'Graveyard', elixir: 5, type: 'Spell', rarity: 'Legendary', arena: 12 },
  { key: 'the-log', name: 'The Log', elixir: 2, type: 'Spell', rarity: 'Legendary', arena: 11 },
  { key: 'tornado', name: 'Tornado', elixir: 3, type: 'Spell', rarity: 'Epic', arena: 15 },
  { key: 'clone', name: 'Clone', elixir: 3, type: 'Spell', rarity: 'Epic', arena: 15 },
  { key: 'earthquake', name: 'Earthquake', elixir: 3, type: 'Spell', rarity: 'Rare', arena: 12 },
  { key: 'barbarian-barrel', name: 'Barbarian Barrel', elixir: 2, type: 'Spell', rarity: 'Epic', arena: 9 },
  { key: 'heal-spirit', name: 'Heal Spirit', elixir: 1, type: 'Troop', rarity: 'Rare', arena: 13 },
  { key: 'giant-snowball', name: 'Giant Snowball', elixir: 2, type: 'Spell', rarity: 'Common', arena: 8 },
  { key: 'royal-delivery', name: 'Royal Delivery', elixir: 3, type: 'Spell', rarity: 'Common', arena: 14 },
  { key: 'party-rocket', name: 'Party Rocket', elixir: 5, type: 'Spell', rarity: 'Legendary', arena: 15 },

  { key: 'little-prince', name: 'Little Prince', elixir: 3, type: 'Troop', rarity: 'Champion', arena: 0 },
  { key: 'goblin-demolisher', name: 'Goblin Demolisher', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'goblin-machine', name: 'Goblin Machine', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 0 },
  { key: 'suspicious-bush', name: 'Suspicious Bush', elixir: 2, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'goblinstein', name: 'Goblinstein', elixir: 5, type: 'Troop', rarity: 'Champion', arena: 0 },
  { key: 'rune-giant', name: 'Rune Giant', elixir: 4, type: 'Troop', rarity: 'Epic', arena: 0 },
  { key: 'berserker', name: 'Berserker', elixir: 2, type: 'Troop', rarity: 'Common', arena: 0 },
  { key: 'boss-bandit', name: 'Boss Bandit', elixir: 6, type: 'Troop', rarity: 'Champion', arena: 0 },
  { key: 'ronin', name: 'Ronin', elixir: 5, type: 'Troop', rarity: 'Legendary', arena: 0 },
  { key: 'minion-giant', name: 'Minion Giant', elixir: 4, type: 'Troop', rarity: 'Rare', arena: 0 },
  { key: 'spirit-empress', name: 'Spirit Empress', elixir: 6, type: 'Troop', rarity: 'Legendary', arena: 0 },
  { key: 'void', name: 'Void', elixir: 5, type: 'Spell', rarity: 'Epic', arena: 0 },
  { key: 'goblin-curse', name: 'Goblin Curse', elixir: 2, type: 'Spell', rarity: 'Epic', arena: 0 },
  { key: 'vines', name: 'Vines', elixir: 3, type: 'Spell', rarity: 'Epic', arena: 0 },
]

