// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv'
import { defineConfig } from 'prisma/config'

// Next.js loads `.env.local` before `.env`, so we do the same to keep one source
// of truth for DATABASE_URL. dotenv does not overwrite keys that already exist,
// which is why `.env.local` is read first.
loadEnv({ path: '.env.local' })
loadEnv()

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
})
